config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    member do
      patch 'done'
      patch 'undo'
    end
  end
  get 'calendar', to: 'tasks#calendar'
  get 'week', to: 'tasks#week'
  get 'day', to: 'tasks#day'
  devise_for :users

  root to: 'tasks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  def start_time
        self.due_date ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :tasks, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = current_user.tasks.all

  end

  def calendar
    @tasks = current_user.tasks.all
  end
  def week
    beginning = Date.today.beginning_of_week
    end_week = Date.today.end_of_week
    tasks = current_user.tasks.all
    @tasks = []
    tasks.each do |task|
      if task.due_date.between?(beginning, end_week)
        @tasks << task
      end
    end
  end
  def day
    tasks = current_user.tasks.all
    @tasks = []
    tasks.each do |task|
      if task.due_date == Date.today
        @tasks << task
      end
    end
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)
    @task.user = current_user
    @task.due_date = Time.parse(task_params[:due_date])

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path , notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_path, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def done
   @task = current_user.tasks.find(params[:id])
   @task.done = true
   @task.save
   redirect_to tasks_path
 end
 def undo
   @task = current_user.tasks.find(params[:id])
   @task.done = false
   @task.save
   redirect_to tasks_path
 end

 private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :description, :done, :user_id, :due_date)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>TODO</title>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <%= favicon_link_tag asset_path('emoji.png') %>
  <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_pack_tag 'application' %> <!-- NEW! -->
  <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
  <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="/manifest.json">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">
<link rel="manifest" href="/manifest.json" />
<meta name="apple-mobile-web-app-capable" content="yes"></head>
<body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/sidebar' %>
  <%= render 'shared/flashes' %>
  <%= yield %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <nav class="topnav">
    <a href="#" onclick="openNav()">
      <svg width="30" height="30" id="icoOpen">
        <path d="M0,5 30,5" stroke="white" stroke-width="5"/>
        <path d="M0,14 30,14" stroke="white" stroke-width="5"/>
        <path d="M0,23 30,23" stroke="white" stroke-width="5"/>
      </svg>
    </a>
  </nav>


  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% unless user_signed_in? %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div id="sideNavigation" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <ul>
    <br>
    <% if user_signed_in? %>

      <%= link_to t(".sign_in", default: "My tasks"), tasks_path, class: "link-side-bar" %>
      <%= link_to t(".sign_in", default: "My calendar"), calendar_path, class: "link-side-bar" %>
      <%= link_to t(".sign_in", default: "Today"), day_path, class: "link-side-bar" %>
      <%= link_to t(".sign_in", default: "Week"), week_path, class: "link-side-bar" %>
      <%= link_to t(".sign_in", default: "Logout"), destroy_user_session_path, method: :delete, class: "link-side-bar" %>

    <%else %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "link-side-bar" %>
      <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path, class: "link-side-bar" %>
    <% end %>
  </ul>
</div>

<script>
function openNav() {
  var width = window.innerWidth;

  if (width < 1030) {
    document.getElementById("sideNavigation").style.zIndex = "101";
    document.getElementById("sideNavigation").style.width = "100%";
    document.getElementById("sideNavigation").style.display = "flex";
    document.getElementById("sideNavigation").style.justifyContent = "center";
    document.getElementById("main").style.marginLeft = "250px";
  }
  else {
    document.getElementById("sideNavigation").style.width = "250px";
    document.getElementById("main").style.marginLeft = "250px"; }
  }

function closeNav() {
    document.getElementById("sideNavigation").style.width = "0";
    document.getElementById("main").style.marginLeft = "0";
}
</script>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view, class: 'calendar-link' %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view, class: 'calendar-link' %>
  </div>

  <table class="table ">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tasks/_form.html.erb
<div class="container flex center">
  <div class="form-style">

    <%= simple_form_for(@task) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :name, class: "my-form" %>
      <%= f.input :description %>
      <%= f.input :due_date, as: :string, required: false, input_html: {class: "datepicker"} %>

    </div>

    <div class="form-inputs">
      <%= f.button :submit, "Go", class: "btn btn-warning" %>
    </div>
    <% end %>
  </div>
</div>

app/views/tasks/calendar.html.erb
<%= month_calendar events: @tasks do |date, tasks| %>
  <%= date.day %>

  <% tasks.each do |task| %>
    <ul>
      <li><%= link_to task.name, task_path(task.id) %></li>
    </ul>
  <% end %>
<% end %>

app/views/tasks/calendar_task.html.erb
<%= month_calendar events: @tasks do |date, tasks| %>
  <%= date.day %>

  <% tasks.each do |task| %>
    <div>
      <%= task.name %>
    </div>
  <% end %>
<% end %>

app/views/tasks/day.html.erb
<div class="slide-container">

  <div class="justify_logo">
    <%= link_to  new_task_path do %>
      <p><i class="far fa-plus-square FA-key add"></i></p>
    <% end %>
  </div>


  <div class="container">
    <div class="row">
      <% @tasks.each do |task| %>

      <div class="col-xs-12 col-sm-4" style="padding: 23px;">
        <!-- insert <div class="card"> -->
          <div class="card" >


            <% if task.done == true  %>
            <div class="done"></div>
            <div class="card-category"><%= task.due_date.strftime("%B %d, %Y") %></div>
            <% elsif task.done == false && Date.current > task.due_date %>
            <div class="late"></div>
            <div class="card-category"><%= task.due_date.strftime("%B %d, %Y") %>
              <p ><%= Date.today.day - task.due_date.day %> days late</p>
            </div>
            <% elsif task.done == false && Date.current < task.due_date %>
            <div class="early"></div>
            <div class="card-category"><%= task.due_date.strftime("%B %d, %Y") %>
              <p ><%= Date.today.day - task.due_date.day %> days left</p>
            </div>


            <% end %>
            <div class="card-description">
              <h2><%= task.name %></h2>
              <p><%= task.description %></p>
            </div>

          </div>

          <div class="clash-card__unit-stats clash-card__unit-stats--barbarian clearfix">
            <% if task.done == false %>

              <div class="one-third">
                <div class="stat-value"><%= link_to "done",  done_task_path(task.id), method: :patch, class: 'event-link' %></div>
              </div>
              <div class="one-third">
                <div class="stat-value"><%= link_to 'Edit', edit_task_path(task), class: 'event-link' %></div>
              </div>
              <div class="one-third no-border">
                <div class="stat-value"><%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' }, class: 'event-link' %></div>
              </div>

            <% else %>

              <div class="one-third">
                <div class="stat-value"><%= link_to "undo",  undo_task_path(task.id), method: :patch, class: 'event-link'  %></div>
              </div>
              <div class="one-third">
                <div class="stat-value"><%= link_to 'Edit', edit_task_path(task), class: 'event-link' %></div>
              </div>
              <div class="one-third no-border">
                <div class="stat-value"><%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' }, class: 'event-link' %></div>
              </div>

            <% end %>
          </div>

        </div>
        <!-- row -->

      <% end %>
      </div>
      <!-- container -->
    </div>
    <!-- slide -->
  </div>

app/views/tasks/edit.html.erb
<h1 style="text-align: center; color: orange;">Editing Task</h1>

<%= render 'form', task: @task %>

<div style="text-align: center; "><%= link_to 'Show', @task %> |
  <%= link_to 'Back', tasks_path %></div>

app/views/tasks/index.html.erb
<div class="slide-container">

  <div class="justify_logo">
    <%= link_to  new_task_path do %>
      <p><i class="far fa-plus-square FA-key add"></i></p>
    <% end %>
  </div>


  <div class="container">
    <div class="row">
      <% @tasks.each do |task| %>

      <div class="col-xs-12 col-sm-4" style="padding: 23px;">
        <!-- insert <div class="card"> -->
          <div class="card" >


            <% if task.done == true  %>
            <div class="done"></div>
            <div class="card-category"><%= task.due_date.strftime("%B %d, %Y") %></div>
            <% elsif task.done == false && Date.current >= task.due_date %>
            <div class="late"></div>
            <div class="card-category"><%= task.due_date.strftime("%B %d, %Y") %>
              <p ><%= Date.today.day - task.due_date.day %> days late</p>
            </div>
            <% elsif task.done == false && Date.current < task.due_date %>
            <div class="early"></div>
            <div class="card-category"><%= task.due_date.strftime("%B %d, %Y") %>
              <p ><%= task.due_date.day - Date.today.day %> days left</p>
            </div>


            <% end %>
            <div class="card-description">
              <h2><%= task.name %></h2>
              <p><%= task.description %></p>
            </div>

          </div>

          <div class="clash-card__unit-stats clash-card__unit-stats--barbarian clearfix">
            <% if task.done == false %>

              <div class="one-third">
                <div class="stat-value"><%= link_to "done",  done_task_path(task.id), method: :patch, class: 'event-link' %></div>
              </div>
              <div class="one-third">
                <div class="stat-value"><%= link_to 'Edit', edit_task_path(task), class: 'event-link' %></div>
              </div>
              <div class="one-third no-border">
                <div class="stat-value"><%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' }, class: 'event-link' %></div>
              </div>

            <% else %>

              <div class="one-third">
                <div class="stat-value"><%= link_to "undo",  undo_task_path(task.id), method: :patch, class: 'event-link'  %></div>
              </div>
              <div class="one-third">
                <div class="stat-value"><%= link_to 'Edit', edit_task_path(task), class: 'event-link' %></div>
              </div>
              <div class="one-third no-border">
                <div class="stat-value"><%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' }, class: 'event-link' %></div>
              </div>

            <% end %>
          </div>

        </div>
        <!-- row -->

      <% end %>
      </div>
      <!-- container -->
    </div>
    <!-- slide -->
  </div>

app/views/tasks/new.html.erb
<div class="back-link"><%= link_to tasks_path do %>
  <i class="fas fa-arrow-left FA-key"  style="padding-left: 20px;"></i>
  <% end %>
</div>
<h1 style="text-align:center;" class="devise-links login">New Task</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
  <div class="back-link"><%= link_to tasks_path do %>
  <i class="fas fa-arrow-left FA-key"  style="padding-left: 20px;"></i>
  <% end %>
</div>
<div class="slide-container">

  <div class="justify_logo">

    <%= link_to  new_task_path do %>
      <p><i class="far fa-plus-square FA-key add"></i></p>
    <% end %>
  </div>


  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12" style="padding: 23px;">
        <!-- insert <div class="card"> -->
          <div class="card" >


            <% if @task.done == true  %>
            <div class="done"></div>
            <div class="card-category"><%= @task.due_date.strftime("%B %d, %Y") %></div>
            <% elsif @task.done == false && Date.current > @task.due_date %>
            <div class="late"></div>
            <div class="card-category"><%= @task.due_date.strftime("%B %d, %Y") %>
              <p ><%= Date.today.day - @task.due_date.day %> days late</p>
            </div>
            <% elsif @task.done == false && Date.current < @task.due_date %>
            <div class="early"></div>
            <div class="card-category"><%= @task.due_date.strftime("%B %d, %Y") %>
              <p ><%= Date.today.day - @task.due_date.day %> days left</p>
            </div>


            <% end %>
            <div class="card-description">
              <h2><%= @task.name %></h2>
              <p><%= @task.description %></p>
            </div>

          </div>

          <div class="clash-card__unit-stats clash-card__unit-stats--barbarian clearfix">
            <% if @task.done == false %>

              <div class="one-third">
                <div class="stat-value"><%= link_to "done",  done_task_path(@task), method: :patch, class: 'event-link' %></div>
              </div>
              <div class="one-third">
                <div class="stat-value"><%= link_to 'Edit', edit_task_path(@task), class: 'event-link' %></div>
              </div>
              <div class="one-third no-border">
                <div class="stat-value"><%= link_to 'Destroy', @task, method: :delete, data: { confirm: 'Are you sure?' }, class: 'event-link' %></div>
              </div>

            <% else %>

              <div class="one-third">
                <div class="stat-value"><%= link_to "undo",  undo_task_path(@task), method: :patch, class: 'event-link'  %></div>
              </div>
              <div class="one-third">
                <div class="stat-value"><%= link_to 'Edit', edit_task_path(@task), class: 'event-link' %></div>
              </div>
              <div class="one-third no-border">
                <div class="stat-value"><%= link_to 'Destroy', @task, method: :delete, data: { confirm: 'Are you sure?' }, class: 'event-link' %></div>
              </div>

            <% end %>
          </div>

        </div>
        <!-- row -->


      </div>
      <!-- container -->
    </div>
    <!-- slide -->
  </div>

app/views/tasks/week.html.erb
<div class="slide-container">

  <div class="justify_logo">
    <%= link_to  new_task_path do %>
      <p><i class="far fa-plus-square FA-key add"></i></p>
    <% end %>
  </div>


  <div class="container">
    <div class="row">
      <% @tasks.each do |task| %>

      <div class="col-xs-12 col-sm-4" style="padding: 23px;">
        <!-- insert <div class="card"> -->
          <div class="card" >


            <% if task.done == true  %>
            <div class="done"></div>
            <div class="card-category"><%= task.due_date.strftime("%B %d, %Y") %></div>
            <% elsif task.done == false && Date.current > task.due_date %>
            <div class="late"></div>
            <div class="card-category"><%= task.due_date.strftime("%B %d, %Y") %>
              <p ><%= Date.today.day - task.due_date.day %> days late</p>
            </div>
            <% elsif task.done == false && Date.current < task.due_date %>
            <div class="early"></div>
            <div class="card-category"><%= task.due_date.strftime("%B %d, %Y") %>
              <p ><%= Date.today.day - task.due_date.day %> days left</p>
            </div>


            <% end %>
            <div class="card-description">
              <h2><%= task.name %></h2>
              <p><%= task.description %></p>
            </div>

          </div>

          <div class="clash-card__unit-stats clash-card__unit-stats--barbarian clearfix">
            <% if task.done == false %>

              <div class="one-third">
                <div class="stat-value"><%= link_to "done",  done_task_path(task.id), method: :patch, class: 'event-link' %></div>
              </div>
              <div class="one-third">
                <div class="stat-value"><%= link_to 'Edit', edit_task_path(task), class: 'event-link' %></div>
              </div>
              <div class="one-third no-border">
                <div class="stat-value"><%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' }, class: 'event-link' %></div>
              </div>

            <% else %>

              <div class="one-third">
                <div class="stat-value"><%= link_to "undo",  undo_task_path(task.id), method: :patch, class: 'event-link'  %></div>
              </div>
              <div class="one-third">
                <div class="stat-value"><%= link_to 'Edit', edit_task_path(task), class: 'event-link' %></div>
              </div>
              <div class="one-third no-border">
                <div class="stat-value"><%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' }, class: 'event-link' %></div>
              </div>

            <% end %>
          </div>

        </div>
        <!-- row -->

      <% end %>
      </div>
      <!-- container -->
    </div>
    <!-- slide -->
  </div>